name: CI

on: [push]

jobs:
  build-test:
    permissions: write-all
    runs-on: ubuntu-latest
#    services:
#      mysql:
#        image: mysql:8.0
#        env:
#          # The MySQL docker container requires these environment variables to be set
#          # so we can create and migrate the test database.
#          # See: https://hub.docker.com/_/mysql
#          MYSQL_DATABASE: "pdo_debugging_tests"
#          MYSQL_ROOT_PASSWORD: "rootpass"
#        ports:
#          # Opens port 3306 on service container and host
#          # https://docs.github.com/en/actions/using-containerized-services/about-service-containers
#          - 3306:3306
#          # Before continuing, verify the mysql container is reachable from the ubuntu host
#22        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - uses: php-actions/composer@v6
        with:
          php_version: "8.3"

      - name: actions-setup-mysql
        uses: shogo82148/actions-setup-mysql@v1.35.0
        with:
          mysql-version: "mariadb-10.6"
      - run: mysql -uroot < tests/config/structure.sql

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: "coverage"
#          DATABASE_NAME: "pdo_debugging_tests"
#          DATABASE_USERNAME: "root"
#          DATABASE_PASSWORD: "rootpass"
#          DATABASE_ENDPOINT: "127.0.0.1" # Will not work with 'localhost', since that will try a Unix socket connection (!)
        with:
          php_version: "8.3"
          php_extensions: "xdebug, pdo_mysqli"
          bootstrap: "vendor/autoload.php"
          configuration: "build/config/phpunit.xml"
          test_suffix: "Test.php"
          coverage_clover: "coverage.xml"
#          args: --display-warnings --display-errors

      - name: Send code coverage report to Codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
